# Generated by Django 5.0.1 on 2025-02-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasierJudiciaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infractions', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('clean', 'Aucune infraction'), ('condamned', 'Condamné')], default='clean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifications', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('casier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.casierjudiciaire')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
